"""Map model vendor prefixes to real company domains for favicon lookup."""

from __future__ import annotations

VENDOR_DOMAINS: dict[str, str] = {
    "01-ai": "01.ai",
    "aion-labs": "aionlabs.com",
    "ai21": "ai21.com",
    "alibaba": "aliyun.com",
    "allenai": "allenai.org",
    "amazon": "amazon.com",
    "anthracite-org": "anthropic.com",
    "anthropic": "anthropic.com",
    "arcee-ai": "arcee.ai",
    "baidu": "baidu.com",
    "bigcode": "huggingface.co",
    "bytedance": "doubao.com",
    "bytedance-seed": "doubao.com",
    "cohere": "cohere.com",
    "cognitivecomputations": "huggingface.co",
    "deepseek": "deepseek.com",
    "dots-studio": "dots.studio",
    "google": "google.com",
    "gryphe": "gryphe.com",
    "huggingface": "huggingface.co",
    "ibm-granite": "ibm.com",
    "inception": "inceptionlabs.ai",
    "inclusionai": "inclusion.ai",
    "kwaipilot": "kuaishou.com",
    "liquid": "liquid.ai",
    "mancer": "openrouter.ai",
    "meituan": "meituan.com",
    "meta": "meta.com",
    "meta-llama": "meta.com",
    "microsoft": "microsoft.com",
    "minimax": "minimax.io",
    "minimaxai": "minimax.io",
    "mistral": "mistral.ai",
    "mistral-ai": "mistral.ai",
    "mistralai": "mistral.ai",
    "moonshot-ai": "moonshot.ai",
    "moonshotai": "moonshot.ai",
    "morph": "morph.so",
    "nex-agi": "nexagi.ai",
    "opencode": "opencode.ai",
    "nousresearch": "nousresearch.com",
    "nvidia": "nvidia.com",
    "openai": "openai.com",
    "openrouter": "openrouter.ai",
    "perceptron": "perceptron.ai",
    "perplexity": "perplexity.ai",
    "poolside": "poolside.ai",
    "qwen": "aliyun.com",
    "reka": "reka.ai",
    "rekaai": "reka.ai",
    "relace": "relace.ai",
    "sakana": "sakana.ai",
    "sao10k": "huggingface.co",
    "stealth": "openrouter.ai",
    "stepfun": "stepfun.com",
    "stepfun-ai": "stepfun.com",
    "tencent": "tencent.com",
    "thedrummer": "openrouter.ai",
    "thedrift": "openrouter.ai",
    "thinkingmachines": "thinkingmachines.ai",
    "undi95": "huggingface.co",
    "upstage": "upstage.ai",
    "writer": "writer.com",
    "x-ai": "x.ai",
    "xiaomi": "xiaomi.com",
    "xiaomimimo": "xiaomi.com",
    "z": "z.ai",
    "z-ai": "z.ai",
    "zai-org": "z.ai",
    "deepseek-ai": "deepseek.com",
    "minimaxai": "minimax.io",
    "minimax": "minimax.io",
    "qwen": "aliyun.com",
}


def logo_domain_for_model(model_id: str) -> str:
    """Return the best-known company domain for a ``vendor/model`` ID."""
    if "/" not in model_id:
        return "openrouter.ai"
    vendor = model_id.split("/")[0]
    vendor = vendor.lstrip("~")
    return VENDOR_DOMAINS.get(vendor, f"{vendor}.com")
